### ISSUE TITLE
pre-commit missing hook.yaml

### ISSUE THREAD

**Issue by rotten** [grantjenks/blue#50]
I was trying to configure blue with a pre-commit hook in my repo.

Unfortunately it doesn't work by simply replacing the black repo with the blue repo (and updating the name and version) in my `.pre-commit-config.yaml` .   The pre-commit command complains that the blue repo is missing a `.pre-commit-hooks.yaml` file.

I think it should be as simple as dropping one that looks like the black one in the top level directory.

Here is the black hooks file:
https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml

This was how I configured my `.pre-commit-config.yaml`:
```
repos:
-   repo: https://github.com/grantjenks/blue.git
    rev: v0.6.0
    hooks:
    - id: blue
      args:
        - -l 120
        - -t py38
```

I tried manually configuring a `.pre-commit-hooks.yaml` file in my own repo with the blue id.  Not surprisingly, that didn't really help.  I'm not quite sure yet how to get blue to run as a pre-commit hook without that file being in the grantjenks/blue repo top level.  Suggestions?
