### ISSUE TITLE
How to properly use Blue in GitHub Actions?

### ISSUE THREAD

**Issue by eddyyxxyy** [grantjenks/blue#85]

**Comment by wojdatto** [comment]
I just migrated from `black`, and I'm using the same way as before -- [pre-commit](https://pre-commit.com/). It's a great solution to run multiple tools in one process, and it provides a ready-to-use plugin for GitHub Actions.

To enable it, you have to create a config file `.pre-commit-config.yaml` in your repo root; the simplest with just `blue` looks like that:

```yaml
repos:
-   repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
    -   id: blue
```

My `.github/workflows/pre-commit.yaml` looks like this. `pre-commit/action@v2.0.2` does the magic here:

```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - test-me-*
    tags:
      - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
```

And remember that you can very easily run pre-commit locally, hence the name -- it can run all checks AKA hooks before each commit
