### ISSUE TITLE
[docs request] Adding example pre-commit config to README

### ISSUE THREAD

**Issue by jamesbraza** [grantjenks/blue#93]
Can we add an example `pre-commit` hook to the `README`:

```yaml
repos:
  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
```

Source: https://github.com/grantjenks/blue/issues/85#issuecomment-1268923837

Just will save a little bit of thought for developers trying to adopt `blue` via `pre-commit`
